version: '3.1'

services:
  mysql:
    container_name: basedatos
    image: unusuario182372/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=login
    expose:
      - 3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      docker_BD:
        ipv4_address: 172.31.0.3
      docker_proyecto:
        ipv4_address: 172.32.0.3

    restart: always
  php:
    container_name: miservidor
    image: unusuario182372/php:7.0-apache
    ports:
      - 9090:80
    links:
      - mysql
    networks:
      docker_proyecto:
        ipv4_address: 172.32.0.2


